### ISSUE TITLE
low throughput when sending requests via iroha2AsyncClient

### ISSUE THREAD

**Issue by timofeevmd** [hyperledger/iroha-java#433]
Java-SDK commit: e23b548
Iroha2 commit: a62640d8a

During load testing, low throughput was identified when sending queries via Iroha2AsyncClient—no more than 146 RPS, compared to sending queries via Gatling—no more than 1125 RPS.

```
send queries throw Iroha2AsyncClient
findAllAsset - no more than 121 RPS
findAssetById - no more than 145 RPS

send queries throw Gatling
findAllAsset - 22 RPS + 12.3 RPS 429 “Too Many Requests“
findAssetById - up to 1125 RPS at peak load
```

In both cases, the requests and responses were correctly processed by Iroha. more details test1 - test4 on [performance report](https://soramitsu.atlassian.net/wiki/spaces/QA/pages/edit-v2/4759060492) 

Additionally, tests were conducted in the following configuration:
The load generator and Iroha were deployed in the same Kubernetes cluster.

```
Throughput results:
findAssetById: 499 RPS
findAllAsset: 1301 RPS (peak load)
```

It was not possible to determine the cause of the significant increase in throughput.

**Comment by Mingela** [comment]
I'd refrain calling that a bug since functionally it works fine and the expected performance metric for the average usage is fine.

Probably the task here would be directed to conducting a research and comparison of our default HTTP client (ktor) used in the SDK with the one Gatling operates on top of.
The other potential cause (imo) might be related to Gatling's native thread-management implementation and its relation to HTTP client resources.

@timofeevmd please share the tool you're using for performance testing with exact versions and platform. Maybe some libraries (dependencies) will be useful as well.
